### ISSUE TITLE
Scheme: HSBC NIFTY 50 INDEX FUND - Direct Growth' and RTA_Code: 'OLNIGD' is not getting ISIN

### ISSUE THREAD

**Issue by neelambhatnagar-sigfyn** [codereverser/casparser-isin#10]
Even after doing casparser-isin --update, unable to fetch ISIN for following
Scheme: HSBC NIFTY 50 INDEX FUND - Direct Growth'
RTA_Code: 'OLNIGD'

**Comment by codereverser** [comment]
Can you please try again? I've updated the database with latest data.

**Comment by neelambhatnagar-sigfyn** [comment]
Thank you. Have you updated just this fund or is the database now up to date with the all the latest funds especially after the L&T and HSBC merger?

**Comment by codereverser** [comment]
Yes. it should be. I've also released a new version of the module with the latest database.
