### ISSUE TITLE
No matching distribution found for casparser-isin

### ISSUE THREAD

**Issue by 71anshuman** [codereverser/casparser-isin#2]
=> ERROR [stage-0  7/13] RUN pip3 install -U casparser-isin                                                          1.8s
- Facing this issue while trying to install it in `docker` container
------
 > [stage-0  7/13] RUN pip3 install -U casparser-isin:
#10 1.432 Collecting casparser-isin
#10 1.658   Could not find a version that satisfies the requirement casparser-isin (from versions: )
#10 1.660 No matching distribution found for casparser-isin

**Comment by codereverser** [comment]
The modules has a dependency on python versions `>=3.8` . Are you using an older version, by any chance?

**Comment by 71anshuman** [comment]
Hi @codereverser ,
Yes, when I `RUN apt-get install -y python3 python3-pip` then docker is installing `Python 3.7`.
- There is no issue with the package apart from it do you have any idea how to install `python 3.8`?
- I searched by didn't find any working solution for it 😔

**Comment by codereverser** [comment]
Which base image are you using for your container? 

Here's a stripped-down version of a working Dockerfile that I'm using 
```
FROM python:3.8-slim
RUN python3 -m venv /venv
RUN /venv/bin/pip install -U pip wheel setuptools
RUN /venv/bin/pip install -U casparser-isin
CMD /venv/bin/casparser-isin --version
```

**Comment by 71anshuman** [comment]
Actually, I am using `FROM php:7.4-fpm` and need to use it within the PHP container.

**Comment by codereverser** [comment]
Oh. that is tricky. You could try manually installing  python3.8 by including the build instructions from https://github.com/docker-library/python/blob/master/3.8/buster/slim/Dockerfile as both `python:3.8-slim` and `php:7.4-fpm` use the same base image. 

Also here's an experimental Dockerfile that may do the same trick.. (not tested well; may have unintended bugs)

```Dockerfile
FROM php:7.4-fpm-buster
# Copy files from python-3.8 image
COPY --from=python:3.8-slim-buster /usr/local /usr/local
COPY --from=python:3.8-slim-buster /usr/lib   /usr/lib
COPY --from=python:3.8-slim-buster /lib64 /lib64
COPY --from=python:3.8-slim-buster /lib /lib
RUN ldconfig 
# Setup virtual env
RUN python3 -m venv /venv
RUN /venv/bin/pip install -U pip wheel setuptools
RUN /venv/bin/pip install -U casparser-isin
CMD /venv/bin/casparser-isin --version
```

**Comment by 71anshuman** [comment]
Hi @codereverser 
Thanks for the help! BTW it didn't work for me :-).
I am closing this issue as I think it might be [this](https://github.com/codereverser/casparser-isin/issues/2#issuecomment-803228208) is case.
- also, I loved your both packages (casparser & casparser-isin), and also if possible please keep them updated.
- And also can you please provide support for the parsing of the `CAMS` portfolio (MF & Stocks)?

**Comment by codereverser** [comment]
Hey no worries! I tried to port both to python3.6 but they (casparser esp) extensively use the walrus operator for regex match and validation. Might not be worth the effort with more systems adopting python3.8 as base version. 

re; the MF & Stocks portfolio, as far as I am aware CAMS provide only MF portfolio . Do you mean CSDL/NSDL statements? If not, can you please provide a link how to generate the statement from CAMS?

**Comment by 71anshuman** [comment]
Ohh, Yes my bad. I mean `CDSL Consolidated Account Statement (CAS)`
> re; the MF & Stocks portfolio, as far as I am aware CAMS provides only MF portfolio. Do you mean CSDL/NSDL statements? If not, can you please provide a link to how to generate the statement from CAMS?

**Comment by codereverser** [comment]
> Are you planning for the same?

Yeah . that feature is in the pipeline. Don't have enough samples with variations to start the task.
