### ISSUE TITLE
What is the source of this data?

### ISSUE THREAD

**Issue by DartPads** [codereverser/casparser-isin#3]
Thank you for your hard work. If you don't mind can you please tell what is the source of this data. Thanks again

**Comment by codereverser** [comment]
No problem! The db is built by merging data from multiple sources . 
- [BSE StarMF Master data](https://bsestarmf.in/RptSchemeMaster.aspx)  - scheme details with RTA code 
- [AMFI NAV](https://www.amfiindia.com/spages/NAVAll.txt) - AMFI code 
- [Quandl AMFI API Metadata](https://www.quandl.com/data/AMFI-Association-of-Mutual-Funds-in-India) - AMFI code

**Comment by codereverser** [comment]
No problem! The db is built by merging data from multiple sources . 
- [BSE StarMF Master data](https://bsestarmf.in/RptSchemeMaster.aspx)  - scheme details with RTA code 
- [AMFI NAV](https://www.amfiindia.com/spages/NAVAll.txt) - AMFI code 
- [Quandl AMFI API Metadata](https://www.quandl.com/data/AMFI-Association-of-Mutual-Funds-in-India) - AMFI code
