### ISSUE TITLE
Missing funds in the database

### ISSUE THREAD

**Issue by ganeshs** [codereverser/casparser-isin#5]
The below funds seem to be missing or has wrong ids:

Missing:
FTI915-XXXXXX Franklin India Ultra Short Bond Fund- Super Inst. Plan-Segregated Portfolio 1 (erstwhile 8.25% Vodafone Idea Ltd-10jul20-Daily Dividend Option) - Daily - IDCW# Payout

Wrong amc_code: expected "036" vs actual "36"
FTI036-XXXXX Franklin India Prima Fund - GROWTH

Couldn't figure out what's wrong here but the ISIN is not showing up in the parsed output
H60-HDFC Low Duration Fund - Regular Plan - Monthly IDCW# (formerly HDFC Cash Management Fund - Treasury Advantage Plan) - Reinvest

**Comment by codereverser** [comment]
Let me have a look at the first two.. 

regarding the third,  can you please post _partial_ screenshots from the CAS file with the scheme? like
![image](https://user-images.githubusercontent.com/8553055/125069921-087d0900-e0d5-11eb-8f4a-6cba1e33d215.png)
 and the partial json data from the library output like 
 ```json
{
   "scheme":"Aditya Birla Sun Life Floating Rate Fund - Growth-Regular Plan",
   "advisor":"WEALTH",
   "rta_code":"B152IG",
   "type":"DEBT",
   "rta":"CAMS",
   "isin":"INF209K01MG9",
   "amfi":"122644"
}
```

**Comment by ganeshs** [comment]
The third one is a reinvest which is not in the datbase. the database has "hdfc low duration fund - retail - regular plan - monthly idcw payout" but not the reinvest

**Comment by codereverser** [comment]
found some issues with the db creation process. shall fix them asap.

**Comment by codereverser** [comment]
The HDFC one is a bit weird. According to the scheme codes provided by hdfc at [List of scheme codes (external)](https://files.hdfcfund.com/s3fs-public/inline-files/List%20of%20scheme%20codes.pdf) , **60** is the code for dividend payout option while **60D** is for the reinvest option. 

need to tweak the search algorithm to handle special cases like this.

**Comment by codereverser** [comment]
Franklin Templeton funds are going to be managed by CAMS from next Monday (July 19th) onwards, as per https://www.franklintempletonindia.com/investor/customer-services/account-services/transition-to-cams

So it may be better to wait and see if the missing schemes' info can be scraped from CAMS directly which is more open than the current FTAMIL RTA.

**Comment by codereverser** [comment]
@ganeshs I've added some "hacks" for handling these schemes in #6 . can you please review and see if it works for you?

**Comment by ganeshs** [comment]
@codereverser the fix introduces regression issues. Added my comments to the PR

**Comment by codereverser** [comment]
Damn. It looks complex.. Let me work on a better solution. 

Does it fix the issues with Franklin funds, btw?

**Comment by ganeshs** [comment]
Yes, Franklin seems to work.
